# Generated by Django 5.2.8 on 2025-11-21 07:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО автора:')),
                ('birth_date', models.CharField(max_length=100, verbose_name='Дата рождения автора:')),
                ('photo', models.ImageField(upload_to='authors/', verbose_name='Фото автора:')),
                ('biography', models.TextField(verbose_name='Биография автора:')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО сотрудника:')),
                ('position', models.CharField(max_length=100, verbose_name='Должность сотрудника:')),
                ('hire_date', models.CharField(max_length=100, verbose_name='Дата найма сотрудника:')),
                ('photo', models.ImageField(upload_to='employees/', verbose_name='Фото сотрудника:')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/', verbose_name='Фото к отзыву:')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта:')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона:')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес доставки:')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Фото пользователя:')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Названия книги:')),
                ('description', models.TextField(verbose_name='Описания книги:')),
                ('pub_date', models.CharField(max_length=4, verbose_name='Дата публикации:')),
                ('price', models.IntegerField(verbose_name='Цена книги:')),
                ('photo', models.ImageField(upload_to='books/', verbose_name='Фото книги:')),
                ('authors', models.ManyToManyField(to='shop.authors', verbose_name='Автор книги:')),
                ('genres', models.ManyToManyField(to='shop.genres', verbose_name='Жанр книги:')),
                ('languages', models.ManyToManyField(to='shop.languages', verbose_name='Язык книги:')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество книг:')),
                ('book', models.ManyToManyField(to='shop.book', verbose_name='Книга:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь:')),
            ],
        ),
        migrations.AddField(
            model_name='authors',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.countries', verbose_name='Страна автора:'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=6, unique=True, verbose_name='Номер заказа:')),
                ('total_price', models.IntegerField(verbose_name='Общая цена заказа:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления заказа:')),
                ('book', models.ManyToManyField(to='shop.book', verbose_name='Книга:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь:')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес доставки:')),
                ('delivery_date', models.CharField(max_length=100, verbose_name='Дата доставки:')),
                ('status', models.CharField(default='В ожидании', max_length=100, verbose_name='Статус доставки:')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.employee', verbose_name='Сотрудник доставки:')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='Заказ:')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100, verbose_name='Способ оплаты:')),
                ('status', models.CharField(default='В ожидании', max_length=100, verbose_name='Статус оплаты:')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты:')),
                ('amount', models.IntegerField(verbose_name='Сумма оплаты:')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='Заказ:')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(verbose_name='Рейтинг:')),
                ('comment', models.TextField(verbose_name='Комментарий:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания отзыва:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления отзыва:')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.book', verbose_name='Книга:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь:')),
                ('images', models.ManyToManyField(blank=True, to='shop.reviewimage', verbose_name='Фото к отзыву:')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='review',
            field=models.ManyToManyField(blank=True, to='shop.review', verbose_name='Отзывы о сотруднике:'),
        ),
        migrations.AddField(
            model_name='authors',
            name='review',
            field=models.ManyToManyField(blank=True, to='shop.review', verbose_name='Отзывы об авторе:'),
        ),
    ]
