# Generated by Django 5.2.8 on 2025-12-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='genres',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='languages',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='birth_date',
            field=models.CharField(help_text='Формат: ДД.ММ.ГГГГ', max_length=100, verbose_name='Дата рождения автора:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.CharField(help_text='Формат: ГГГГ', max_length=4, verbose_name='Дата публикации:'),
        ),
    ]
