# Generated by Django 5.2.8 on 2025-11-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='birth_date',
            field=models.CharField(help_text='Формат: ДД.ММ.ГГГГ', max_length=100, verbose_name='Дата рождения автора:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.CharField(help_text='Формат: ГГГГ', max_length=4, verbose_name='Дата публикации:'),
        ),
    ]
