# Generated by Django 4.2 on 2025-12-03 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_authors_birth_date_alter_book_pub_date'),
        ('shop', '0002_authors_slug_book_slug_countries_slug_genres_slug_and_more'),
    ]

    operations = [
    ]
