# Generated by Django 5.2.8 on 2025-12-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_authors_slug_book_slug_countries_slug_genres_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кол-во в наличии:'),
        ),
    ]
