# Generated by Django 5.2.8 on 2025-12-06 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_book_stock'),
        ('shop', '0003_merge_20251203_1854'),
    ]

    operations = [
    ]
