# Generated by Django 5.2.8 on 2025-12-06 06:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_merge_0003_book_stock_0003_merge_20251203_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления:'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False, verbose_name='Товар вычтен:'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата доставки:'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.employee', verbose_name='Сотрудник доставки:'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Завершен', 'Завершен'), ('Отменен', 'Отменен')], default='В ожидании', max_length=100, verbose_name='Статус оплаты:'),
        ),
    ]
