# Generated by Django 5.2.8 on 2025-12-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_delivery_created_at_delivery_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_status',
            field=models.CharField(choices=[('Активен', 'Активен'), ('Отменен', 'Отменен')], default='Активен', max_length=20, verbose_name='Статус отмены:'),
        ),
    ]
