# Generated by Django 5.2.8 on 2025-12-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_cancel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров:'),
        ),
    ]
