# Generated by Django 5.2.8 on 2025-12-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_add_bookview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
