# Generated by Django 5.2.8 on 2025-12-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_add_usercartitem'),
        ('shop', '0009_alter_bookview_id'),
    ]

    operations = [
    ]
