# Generated by Django 5.2.8 on 2025-12-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_merge_0009_add_usercartitem_0009_alter_bookview_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercartitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
